# Generated by Django 5.0.3 on 2024-04-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('employers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employers', verbose_name='Работодатель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('vacancies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.vacancies', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name_plural': 'Отлик на вакансию',
            },
        ),
    ]
