# Generated by Django 5.0.3 on 2024-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_responsevacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание вакансии'),
        ),
    ]
