# Generated by Django 5.0.3 on 2024-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_vacancies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsevacancies',
            name='is_invitation',
            field=models.BooleanField(default=False, verbose_name='Приглашение на собеседование'),
        ),
    ]
