# Generated by Django 5.0.3 on 2024-04-05 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_responsevacancies_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsevacancies',
            name='vacancies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.vacancies', verbose_name='Вакансия'),
        ),
    ]
